version: '3.5'
services:
  api1:
    # image: iancambrea/rinha-python-sanic
    build: .
    hostname: api1
    environment:
      PORT: 8080
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    command: "sanic main:app -u='/tmp/api1.sock' --no-access-logs --single-process"
    volumes:
      - socks:/tmp
    network_mode: host

  api2:
    # image: iancambrea/rinha-python-sanic
    build: .
    hostname: api1
    environment:
      PORT: 8081
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    command: "sanic main:app -u='/tmp/api2.sock' --no-access-logs --single-process"
    volumes:
      - socks:/tmp
    network_mode: host

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - socks:/tmp
    network_mode: host
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rinha
    container_name: db
    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
    command: postgres -c shared_buffers=384MB -c max_connections=400 -c log_min_messages=FATAL
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1GB'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --dbname=rinha --username=user"]
        interval: 2s
        timeout: 2s
        retries: 30
    network_mode: host

  redis:
    image: redis:latest
    network_mode: host
    command: redis-server --save "" --appendonly no --maxclients 10000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

volumes:
  socks:
